### PR TITLE
Adding images model

### PR DESCRIPTION
**Pull request by Rohit-L**

### CODE REVIEW

**Comment by Rohit-L** [comment]
Completed two issues here:
1) Implementing ability to add images
2) Implementing persistence of images and sizing them appropriately

**Comment by leoi11** [comment]
Hi Rohit, I'm the reviewer of this issue: https://github.com/AppFolioOnboarding/Rohit/issues/2

I have some suggestion of good practices in the future:
1. Reference the issue your PR is addressing so that others looking at your change can get a good understanding of what problem you're solving.
2. Do not close an issue until a PR has been merged to master. This help others understand the status of your issue. (Think about if the PR isn't not merged in the end, and you have already closed the issue.)
3. Address one issue at a time: There are many benefits of keeping things small. For example, it helps the reviewer focus on a specific problem you're solving. It also can be merged to master independently, which eventually allow you to merge things in quicker. Imagine doing everything altogether, when people review it, if they have a comment on feature A, but not on feature B, you'll not be able to merge the whole changeset in unless you have addressed the comments for feature A.

**Comment by leoi11** [comment]
UPDATE: We are doing ropes slightly differently for the internship program, so I just realized your mentor will be peer reviewing your change instead. Hopefully that's helpful information for you above though! Welcome to AppFolio :)

**Comment by Rohit-L** [comment]
Thank you, Leo. I will definitely keep your suggestions in mind!

**Pull request closed without merging**
